// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Sika.AnimName
{
    using System;
    using UnityEngine;
    using System.Collections;
    
    
    [System.SerializableAttribute()]
    public sealed class AnimName
    {
        
        private string _Id;
        
        // 这是Id属性
        public string AnimName
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
}
