// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections;


[System.SerializableAttribute()]
public class AnimName
{
    
    public static string Trail3 = "Trail3";
    
    public static string Trail4 = "Trail4";
    
    public static string Trail2 = "Trail2";
    
    public static string Trail1 = "Trail1";
    
    public static string TanPool = "TanPool";
    
    public static string XiaoDuPool = "XiaoDuPool";
    
    public static string LuoYa = "LuoYa";
    
    public static string ChenShanChi = "ChenShanChi";
    
    public static string DirtyPool = "DirtyPool";
    
    public static string SecondChenDian = "SecondChenDian";
    
    public static string HunNingPool = "HunNingPool";
    
    public static string CuGeShan2 = "CuGeShan2";
    
    public static string YanYang = "YanYang";
    
    public static string LiXinTuoShui = "LiXinTuoShui";
    
    public static string DuoJiXiaoHuaPool = "DuoJiXiaoHuaPool";
    
    public static string FirstChenDian = "FirstChenDian";
    
    public static string CuGeShan1 = "CuGeShan1";
    
    public static string XiGeShan1 = "XiGeShan1";
    
    public static string XiGeShan2 = "XiGeShan2";
    
    public static string GuFengJi = "GuFengJi";
}

public class WayPointName
{
    
    public static string WayPoint4 = "WayPoint4";
    
    public static string WayPoint3 = "WayPoint3";
    
    public static string WayPoint2 = "WayPoint2";
    
    public static string WayPoint1 = "WayPoint1";
}
